name: "PhilHealth_eKonsultaSQL"

services:
  postgres_db:
    image: postgres:16
    container_name: PhilHealth_eKonsultaSQL
    restart: always
    environment:
      POSTGRES_DB: eKonsulta_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "9095:5432"
    volumes:
      - pg_eKonsulta_data:/var/lib/postgresql/data

volumes:
  pg_eKonsulta_data:
